apps/landr/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
    # url(r'^success$', views.success, name="success"),
]

apps/wishlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add_item$', views.add_item, name="add_item"),
    url(r'^create$', views.create, name="create"),
    url(r'^delete$', views.delete, name="delete"),
    url(r'^show/(?P<id>\d+)', views.show, name="show"),
    url(r'^add_wish$', views.add_wish, name="add_wish"),
]

buffalo_soldier/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.landr.urls', namespace='landr')),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace="wishlist"))
]

apps/landr/models.py
from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.

class UserManager(models.Manager):
    def new_user(self, data):
        errors = []

        if not data['name']:
            errors.append("Name can not be blank.")
        if len(data['name']) < 3:
            errors.append("Name must be longer than 3 characters")
        if not data['username']:
            errors.append("Username can not be blank.")
        if len(data['username']) < 3:
            errors.append("Username must be longer than 3 characters")
        if not data['email']:
            errors.append("Email can not be blank.")
        elif not EMAIL_REGEX.match(data['email']):
            errors.append("Invalid Email")
        if not data['password']:
            errors.append("Password can not be blank.")
        elif len(data['password']) < 8:
            errors.append("Password must be longer than 8 characters.")
        if not data['con_password']:
            errors.append("Confirm Password can not be blank.")
        if data['password'] != data['con_password']:
            errors.append("Passwords do not match.")
        if len(data['bday']) < 1:
            errors.append("Invalid Date.")

        response = {}
        if errors:
            response['errors'] = errors
            response['created'] = False
        else:
            password = data['password'].encode()
            hashed = bcrypt.hashpw(password, bcrypt.gensalt())
            new_user = self.create(name=data['name'], username=data['username'], email=data['email'], password=hashed, bday=data['bday'])
            response['created'] = True
            response['new_user'] = new_user

        return response

    def login(self, data):
        errors = []

        if not data['log_email']:
            errors.append("No email was given.")
        if not data['log_password']:
            errors.append("No password was given.")

        response = {}
        if errors:
            response['errors'] = errors
            response['log_in'] = False

        else:
            try:
                user = User.objects.get(email=data['log_email'])
                password = data['log_password'].encode()
                if bcrypt.hashpw(password, user.password.encode()) == user.password.encode():
                    response['log_in'] = True
                    response['user'] = user
            except:
                errors.append("Email does not exist.")
                response['errors'] = errors
                response['log_in'] = False

        return response


class User(models.Model):
    name = models.CharField(max_length=45)
    username = models.CharField(max_length=45)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    bday = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/wishlist/models.py
from django.db import models
from ..landr.models import User
# Create your models here.


class ItemManager(models.Manager):
    def new_item(self, data, creator):
        errors = []

        if not data['product']:
            errors.append("No product given.")
        if len(data['product']) < 3:
            errors.append("Must be more than 3 characters.")

        response = {}
        if errors:
            response['errors'] = errors
            response['created'] = False
        else:
            self.create(name=data['product'], created_by=creator)
            response['created'] = True
        return response


class Item(models.Model):
    name = models.CharField(max_length=45)
    created_by = models.CharField(max_length=45)
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager()

apps/landr/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

# Create your views here.


def index(request):
    return render(request, "landr/index.html")


def register(request):
    if request.method=="POST":
        reg_data = User.objects.new_user(request.POST)
        if reg_data['created']:
            messages.success(request, "{} successfully registered".format(reg_data['new_user'].name))
        else:
            for error in reg_data['errors']:
                messages.error(request, error)
    return redirect('landr:index')


def login(request):
    if request.method == "POST":
        user = User.objects.login(request.POST)
        if user['log_in']:
            request.session['user_id'] = user['user'].id
            request.session['user_name'] = user['user'].name
            return redirect('wishlist:index')
        else:
            for error in user['errors']:
                messages.error(request, error)
            return redirect('landr:index')


def logout(request):
    request.session.clear()
    return redirect("landr:index")

apps/wishlist/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from ..landr.models import User
from .models import Item

# Create your views here.
def index(request):
    context = {
    "my_products": Item.objects.filter(created_by=request.session['user_name']),
    "other_products": Item.objects.exclude(created_by=request.session['user_name']),
    }
    return render(request, 'wishlist/index.html', context)


def add_item(request):
    return render(request, 'wishlist/add_item.html')


def create(request):
    if request.method == "POST":
        creator = request.session['user_name']
        create_data = Item.objects.new_item(request.POST, creator)
        if create_data['created']:
            return redirect('wishlist:index')
        else:
            for error in create_data['errors']:
                messages.error(request, error)
            return redirect('wishlist:add_item')
    return redirect('wishlist:index')


def show(request, id):
    if request.method == "POST":
        this_item = Item.objects.get(id=id)
        context = {
            "item": this_item
        }
        return render(request, 'wishlist/show.html', context)


def add_wish(request):
    if request.method == "POST":
        item = Item.objects.get(id=request.POST['product_id'])
        user = User.objects.get(id=request.session['user_id'])
        item.users.add(user)
    return redirect('wishlist:index')

def delete(request):
    Item.objects.filter(id=request.POST['product_id']).delete()
    return redirect('wishlist:index')

apps/landr/templates/landr/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login/Registration</title>
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
        {% endif %}
        <h1>Registration:</h1>
        <form action="/register" method="post">
            {% csrf_token %}
            <p>Name: <input type="text" name="name"></p>
            <p>Username: <input type="text" name="username"></p>
            <p>Email: <input type="text" name="email"></p>
            <p>Password; <input type="password" name="password"></p>
            <p>Confirm Password: <input type="password" name="con_password"></p>
            <input type="date" name="bday" value="">
            <p><input type="submit" value="Register"></p>
        </form>
        <h1>Login:</h1>
        <form action="/login" method="post">
            {% csrf_token %}
            <p>Email: <input type="text" name="log_email"></p>
            <p>Password: <input type="password" name="log_password"></p>
            <p><input type="submit" value="Login"></p>
        </form>
    </body>
</html>

apps/wishlist/templates/wishlist/add_item.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Item</title>
    </head>
    <body>
        <h1>Create a New Wish List Item</h1>
        {% if messages %}
            {% for message in messages %}
                <p>{{message}}</p>
            {% endfor %}
        {% endif %}
        <a href="{% url 'wishlist:index'%}">Home</a>
        <a href="{% url 'landr:logout'%}">Logout</a>
        <form  action="{% url 'wishlist:create' %}" method="post">
            {% csrf_token %}
            <p><input type="text" name="product" value=""></p>
            <input type="submit" value="Add">
        </form>
    </body>
</html>

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My Wish List</title>
        <style media="screen">
            input {
                border: none;
                background: none;
                color: blue;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h1>Hello, {{request.session.user_name}}</h1>
        <a href="{% url 'landr:logout'%}">Logout</a>
        <h3>Your Wish List</h3>
        <table>
            <tr>
                <th>Item</th>
                <th>Added By</th>
                <th>Date Added</th>
                <th>Action</th>
            </tr>
            {% for wish in my_wishes %}
                <tr>
                    <td><form action="{% url 'wishlist:show' id=product.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{product.name}}">
                        <input type="submit" value="{{product.name}}">
                    </form></td>
                    <td>{{product.created_by}}</td>
                    <td>{{product.created_at}}</td>
                    <td>
                        <form action="{% url 'wishlist:remove_wish'%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{users.id}}">
                            <input type="submit" value="Delete">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            {% for product in my_products %}
                <tr>
                    <td><form action="{% url 'wishlist:show' id=product.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{product.name}}">
                        <input type="submit" value="{{product.name}}">
                    </form></td>
                    <td>{{product.created_by}}</td>
                    <td>{{product.created_at}}</td>
                    <td>
                        <form action="{% url 'wishlist:delete'%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{product.id}}">
                            <input type="submit" value="Delete">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h3>Other Users' Wish List Items</h3>
        <table>
            <tr>
                <th>Item</th>
                <th>Added By</th>
                <th>Date Added</th>
                <th>Action</th>
            </tr>
            {% for product in other_products %}
                <tr>
                    <td><form action="{% url 'wishlist:show' id=product.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{product.name}}">
                        <input type="submit" value="{{product.name}}">
                    </form></td>
                    <td>{{product.created_by}}</td>
                    <td>{{product.created_at}}</td>
                    <td>
                        <form action="{% url 'wishlist:add_wish'%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{product.id}}">
                            <input type="submit" value="Add to my Wishlist">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{% url 'wishlist:add_item'%}">Add Item</a>
    </body>
</html>

apps/wishlist/templates/wishlist/show.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{item.name}}</title>
    </head>
    <body>
        <h1>{{item.name}}</h1>
        <a href="{% url 'wishlist:index'%}">Home</a>
        <a href="{% url 'landr:logout'%}">Logout</a>
    </body>
</html>